In [1]:
import numpy as np

In [2]:
l = [1,5,6,2,3,4]

arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
type(l)

list

In [7]:
# l1 = l + 10  #it will gives a error

l1 = l + [10]

l1

[1, 5, 6, 2, 3, 4, 10]

In [8]:
arr = arr + 10  #it is not possible in list

arr

array([11, 15, 16, 12, 13, 14])

In [10]:
l = [1,5,6,2,3,4]

arr = np.array(l)

arr = arr + 10 + 10 * 9 -40//6

arr

array([ 95,  99, 100,  96,  97,  98])

In [11]:
arr.dtype

dtype('int32')

In [12]:
l = [1,5,6,2,3,4,'9']

arr = np.array(l)

print(arr)
print(arr.dtype)

['1' '5' '6' '2' '3' '4' '9']
<U11


In [13]:
l = [1,5,6,2,3,4,9.0]

arr = np.array(l)

print(arr)
print(arr.dtype)

[1. 5. 6. 2. 3. 4. 9.]
float64


In [14]:
l = [1,5,6,2.0,3,4,'9']

arr = np.array(l, dtype = int)

print(arr, arr.dtype)

[1 5 6 2 3 4 9] int32


In [15]:
l = [1,5,6,2.0,3,4,'9']

arr = np.array(l, dtype = float)

print(arr, arr.dtype)

[1. 5. 6. 2. 3. 4. 9.] float64


In [16]:
l = [1,5,6,2.0,3,4,'9']

arr = np.array(l) #since l constains one string value automatically all values will follow one data type rule

print(arr, arr.dtype)

['1' '5' '6' '2.0' '3' '4' '9'] <U32


In [17]:
l = [1,5,6,2.0,3,4,'9']

arr = np.array(l, dtype = float)
arr = arr + 10 + 10 * 9

arr = arr.astype(int)   #typecasting

print(arr, arr.dtype)

[101 105 106 102 103 104 109] int32


In [19]:
a = np.array([[10,20],
              [30,40],
              [50,60]])

print(a)

[[10 20]
 [30 40]
 [50 60]]


In [22]:
a.shape

(3, 2)

In [23]:
a.ndim

2

In [24]:
print(a+10)

[[20 30]
 [40 50]
 [60 70]]
