In [1]:
a = np.array([[10,20],
              [30,40],
              [50,60]])



<IPython.core.display.Javascript object>

In [2]:
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [3]:
b = np.where(a>=30,a,0)

b

<IPython.core.display.Javascript object>

array([[ 0,  0],
       [30, 40],
       [50, 60]])

In [4]:
b = np.where(a>=40,'yes','no')

b

<IPython.core.display.Javascript object>

array([['no', 'no'],
       ['no', 'yes'],
       ['yes', 'yes']], dtype='<U3')

In [7]:
np.where(((a==30) | (a==50) | (a==60)),305060,a)

<IPython.core.display.Javascript object>

array([[    10,     20],
       [305060,     40],
       [305060, 305060]])

In [6]:
np.where(((a == 30) | (a == 50) | (a == 60)), 304060, a)

<IPython.core.display.Javascript object>

array([[    10,     20],
       [304060,     40],
       [304060, 304060]])

In [9]:
np.random.seed(30)

rm_arr = np.random.random((3,2))

rm_arr

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[0.64414354, 0.38074849],
       [0.66304791, 0.16365073],
       [0.96260781, 0.34666184]])

In [10]:
np.random.seed(20)

rm_arr1 = np.random.random((4))
print(rm_arr1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0.5881308  0.89771373 0.89153073 0.81583748]


In [11]:
np.random.randn(3,2)

<IPython.core.display.Javascript object>

array([[ 0.35753652, -2.34326191],
       [-1.08483259,  0.55969629],
       [ 0.93946935, -0.97848104]])

In [56]:
np.random.randint(10)

<IPython.core.display.Javascript object>

8

In [57]:
np.random.randint(0,100,40)

<IPython.core.display.Javascript object>

array([ 6, 26, 79, 82, 78, 10, 33, 85, 17, 40, 82, 42, 60, 84, 30, 36,  8,
       48, 19, 48, 95, 53, 10, 38,  9, 60, 60, 23, 52, 96, 76, 78, 95, 54,
       81, 73, 27, 39, 87,  9])

In [58]:
np.random.randint(0,100,(4,4))

<IPython.core.display.Javascript object>

array([[14, 31, 56, 56],
       [58, 79, 27, 50],
       [74, 69,  2, 57],
       [23, 95, 25, 41]])

In [59]:
a = np.random.normal(8,2,50)

<IPython.core.display.Javascript object>

array([ 6.07556803,  7.03509818,  7.52106049,  8.91948845,  9.29286033,
        8.97480592,  8.07638494,  9.97897312,  8.28724527,  9.50059586,
        7.18085715, 10.89481409,  7.19093195, 10.29785003,  6.12217902,
        4.1970719 , 10.1908667 ,  7.33291243,  5.11630285,  5.1666665 ,
        4.74099696,  4.36948838,  5.887662  ,  9.10854987,  6.09996398,
        9.7159987 ,  6.93584151, 10.25151771,  8.43731544,  7.21423608,
        7.54260547,  4.84749024,  8.33166602,  9.57759363,  4.07621551,
        4.29592351, 10.18377323,  9.86918171,  6.57642889, 10.88616602,
        9.50462664,  5.33015847,  9.35327934,  9.66221156,  7.26988511,
        8.99354049,  8.5791183 ,  7.05958131, 11.21198528,  7.69267634])